import './EfectoOlas.scss';

export const EfectoOlas = () => {
    return (
        <div className="EfectoOla">
            {/* Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections  */}

            <div className="EfectoOla-container" style={{height: 150, overflow: 'hidden'}}><svg viewBox="0 0 500 150" preserveAspectRatio="none" style={{height: '100%', width: '100%'}}>
                    <path className="EfectoOla-1" d="M-16.64,139.64 C104.68,-149.48 0.85,130.77 502.54,147.55 L513.26,156.42 L0.00,150.00 Z" stroke= "none;"></path>
                </svg>
            </div>
            <div className="EfectoOla-container" style={{height: 150, overflow: 'hidden'}}><svg viewBox="0 0 500 150" preserveAspectRatio="none" style={{height: '100%', width: '100%'}}>
                    <path className="EfectoOla-1" d="M-16.64,139.64 C106.37,176.16 -51.06,-186.00 502.54,147.55 L513.26,156.42 L0.00,150.00 Z" stroke= "none;"></path>
                </svg>
            </div>
            <div className="EfectoOla-container" style={{height: 150, overflow: 'hidden'}}><svg viewBox="0 0 500 150" preserveAspectRatio="none" style={{height: '100%', width: '100%'}}>
                    <path className="EfectoOla-1" d="M-16.64,139.64 C566.31,85.38 455.13,-139.61 502.54,147.55 L513.26,156.42 L0.00,150.00 Z" stroke= "none;"></path>
                </svg>
            </div>
            <div className="EfectoOla-container" style={{height: 130, overflow: 'hidden'}}><svg viewBox="0 0 500 150" preserveAspectRatio="none" style={{height: '100%', width: '100%'}}>
                    <path className="EfectoOla-2" d="M-16.64,139.64 C36.96,189.97 -119.35,-198.83 311.23,161.36 L513.26,156.42 L0.28,151.48 Z" stroke= "none;"></path>
                </svg>
            </div>
            <div className="EfectoOla-container" style={{height: 130, overflow: 'hidden'}}><svg viewBox="0 0 500 150" preserveAspectRatio="none" style={{height: '100%', width: '100%'}}>
                    <path className="EfectoOla-2" d="M-16.64,139.64 C132.89,70.56 415.63,-58.69 521.72,161.36 L513.26,156.42 L0.28,151.48 Z" stroke= "none;"></path>
                </svg>
            </div>
            <div className="EfectoOla-container" style={{height: 90, overflow: 'hidden'}}><svg viewBox="0 0 500 150" preserveAspectRatio="none" style={{height: '100%', width: '100%'}}>
                    <path className="EfectoOla-3" d="M-1.41,154.45 C3.11,-126.78 91.13,68.59 130.07,129.78 L513.26,156.42 L-13.26,152.47 Z" stroke= "none;"></path>
                </svg>
            </div>
            <div className="EfectoOla-container" style={{height: 90, overflow: 'hidden'}}><svg viewBox="0 0 500 150" preserveAspectRatio="none" style={{height: '100%', width: '100%'}}>
                    <path className="EfectoOla-3" d="M39.78,137.67 C180.30,-118.89 113.71,125.83 240.12,147.55 L513.26,156.42 L-13.26,152.47 Z" stroke= "none;"></path>
                </svg>
            </div>
            <div className="EfectoOla-container" style={{height: 90, overflow: 'hidden'}}><svg viewBox="0 0 500 150" preserveAspectRatio="none" style={{height: '100%', width: '100%'}}>
                    <path className="EfectoOla-3" d="M147.01,116.95 C233.92,11.36 306.15,31.09 455.13,166.30 L513.26,156.42 L-13.26,152.47 Z" stroke= "none;"></path>
                </svg>
            </div>
            <div className="EfectoOla-container" style={{height: 90, overflow: 'hidden'}}><svg viewBox="0 0 500 150" preserveAspectRatio="none" style={{height: '100%', width: '100%'}}>
                    <path className="EfectoOla-3" d="M316.87,156.42 C351.30,42.94 491.82,-92.25 503.10,150.50 L513.26,156.42 L0.28,151.48 Z" stroke= "none;"></path>
                </svg>
            </div>
        </div>
    );
};