export function Separador () {
    return (
        <div className="c-tecnologias o-container">
        <div className="c-tecnologias__listado">
            <div className="c-tecnologias__tarjeta">
                <h4 className="c-tecnologias__titulo">Lenguajes programación</h4>
                <ul className="c-tecnologias__ul">
                    <li className="c-tecnologias__li">- HTML5 + CSS3</li>
                    <li className="c-tecnologias__li">- JavaScript</li>
                    <li className="c-tecnologias__li">- PHP</li>
                    <li className="c-tecnologias__li">- MySQL</li>
                    <li className="c-tecnologias__li">- Node js</li>
                    <li className="c-tecnologias__li">- Python</li>
                </ul>
            </div>
            <div className="c-tecnologias__tarjeta">
                <h4 className="c-tecnologias__titulo">Framework & CMS's</h4>
                <ul className="c-tecnologias__ul">
                    <li className="c-tecnologias__li">- React js</li>
                    <li className="c-tecnologias__li">- Jquery</li>
                    <li className="c-tecnologias__li">- SASS</li>
                    <li className="c-tecnologias__li">- Bootstrap 5</li>
                    <li className="c-tecnologias__li">- Wordpress</li>
                    <li className="c-tecnologias__li">- Django</li>
                </ul>
            </div>
            <div className="c-tecnologias__tarjeta">
                <h4 className="c-tecnologias__titulo">Otros complementos</h4>
                <ul className="c-tecnologias__ul">
                    <li className="c-tecnologias__li">- IndexedDb</li>
                    <li className="c-tecnologias__li">- Gulp</li>
                    <li className="c-tecnologias__li">- CRUD MySQL</li>
                    <li className="c-tecnologias__li">- Testing</li>
                    <li className="c-tecnologias__li">- Git + GitHub</li>
                    <li className="c-tecnologias__li">- Patrones de diseño</li>
                </ul>
            </div>
        </div>
        <ul className="c-tecnologias__iconos">
            <li className="c-tecnologias__iconos-li"><i className="fab fa-html5"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fab fa-css3-alt"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fab fa-js-square"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fa-brands fa-php"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fa-solid fa-database"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fab fa-node-js"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fa-brands fa-python"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fab fa-react"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fab fa-sass"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fa-brands fa-bootstrap"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fab fa-wordpress"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fab fa-gulp"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fab fa-npm"></i></li>
            <li className="c-tecnologias__iconos-li"><i className="fa-brands fa-git-alt"></i></li>
        </ul>
         {/* Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections */}

{/*          
        <div className="c-tecnologias__separador c-efecto-ola">
            <div style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
                    <path className="c-efecto__ola-1" d="M-16.64,139.64 C104.68,-149.48 0.85,130.77 502.54,147.55 L513.26,156.42 L0.00,150.00 Z" style="stroke: none;"></path>
                </svg>
            </div>
            <div style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
                    <path className="c-efecto__ola-1" d="M-16.64,139.64 C106.37,176.16 -51.06,-186.00 502.54,147.55 L513.26,156.42 L0.00,150.00 Z" style="stroke: none;"></path>
                </svg>
            </div>
            <div style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
                    <path className="c-efecto__ola-1" d="M-16.64,139.64 C566.31,85.38 455.13,-139.61 502.54,147.55 L513.26,156.42 L0.00,150.00 Z" style="stroke: none;"></path>
                </svg>
            </div>
            <div style="height: 130px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
                    <path className="c-efecto__ola-2" d="M-16.64,139.64 C36.96,189.97 -119.35,-198.83 311.23,161.36 L513.26,156.42 L0.28,151.48 Z" style="stroke: none;"></path>
                </svg>
            </div>
            <div style="height: 130px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
                    <path className="c-efecto__ola-2" d="M-16.64,139.64 C132.89,70.56 415.63,-58.69 521.72,161.36 L513.26,156.42 L0.28,151.48 Z" style="stroke: none;;"></path>
                </svg>
            </div>
            <div style="height: 90px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
                    <path className="c-efecto__ola-3" d="M-1.41,154.45 C3.11,-126.78 91.13,68.59 130.07,129.78 L513.26,156.42 L-13.26,152.47 Z" style="stroke: none;"></path>
                </svg>
            </div>
            <div style="height: 90px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
                    <path className="c-efecto__ola-3" d="M39.78,137.67 C180.30,-118.89 113.71,125.83 240.12,147.55 L513.26,156.42 L-13.26,152.47 Z" style="stroke: none;"></path>
                </svg>
            </div>
            <div style="height: 90px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
                    <path className="c-efecto__ola-3" d="M147.01,116.95 C233.92,11.36 306.15,31.09 455.13,166.30 L513.26,156.42 L-13.26,152.47 Z" style="stroke: none;"></path>
                </svg>
            </div>
            <div style="height: 90px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
                    <path className="c-efecto__ola-3" d="M316.87,156.42 C351.30,42.94 491.82,-92.25 503.10,150.50 L513.26,156.42 L0.28,151.48 Z" style="stroke: none;"></path>
                </svg>
            </div>
        </div> */}
    </div>
    )
}